package work.racka.thinkrchive.utils

import work.racka.thinkrchive.data.model.Thinkpad

object Constants {
    const val BASE_URL = "https://docs.google.com/spreadsheets/d/1cFrYzzAP7i3bzSLKuBMykz3ZNUbf-YPTqRSEAwINy_E/"
    const val THINKPAD_LIST_TABLE = "thinkpad_list"

    val ThinkpadsListPreview = listOf(
        Thinkpad(
            model = "Thinkpad T450",
            imageUrl = "https://raw.githubusercontent.com/racka98/ThinkRchive/main/thinkpad_images/thinkpadt450.png",
            releaseDate = "Jan, 2015",
            series = "T Series",
            marketPriceStart = 250,
            marketPriceEnd = 500,
            processorPlatforms = "Intel 5th Gen",
            processors = "i3-4030U, i5-4300U, i3-5010U, i5-5200U, i5-5300U, i7-5500U, i7-5600U",
            graphics = "Intel HD 5500",
            maxRam = "16GB (2 Slots)",
            displayRes = "1366x768, 1600x900, 1920x1080",
            touchScreen = "Yes",
            screenSize = "14 inch",
            backlitKb = "Yes",
            fingerPrintReader = "Yes",
            kbType = "6 Row, Backlit",
            dualBatt = "Yes",
            internalBatt = "3 Cell",
            externalBatt = "3 Cell, 6 Cell",
            psrefLink = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosVersion = "1.37(JBET73WW)",
            knownIssues = "Other",
            knownIssuesLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            displaysSupported = "AUO, LG, SAM",
            otherMods = "Other",
            otherModsLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosLockIn = "Yes: Display"
        ),
        Thinkpad(
            model = "Thinkpad T450",
            imageUrl = "https://raw.githubusercontent.com/racka98/ThinkRchive/main/thinkpad_images/thinkpadt450.png",
            releaseDate = "Jan, 2015",
            series = "T Series",
            marketPriceStart = 250,
            marketPriceEnd = 500,
            processorPlatforms = "Intel 5th Gen",
            processors = "i5-4300u",
            graphics = "Intel HD 5500",
            maxRam = "16GB (2 Slots)",
            displayRes = "1366x768, 1600x900, 1920x1080",
            touchScreen = "Yes",
            screenSize = "14 inch",
            backlitKb = "Yes",
            fingerPrintReader = "Yes",
            kbType = "6 Row, Backlit",
            dualBatt = "Yes",
            internalBatt = "3 Cell",
            externalBatt = "3 Cell, 6 Cell",
            psrefLink = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosVersion = "1.37(JBET73WW)",
            knownIssues = "Other",
            knownIssuesLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            displaysSupported = "AUO, LG, SAM",
            otherMods = "Other",
            otherModsLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosLockIn = "Yes: Display"
        ),
        Thinkpad(
            model = "Thinkpad T450",
            imageUrl = "https://raw.githubusercontent.com/racka98/ThinkRchive/main/thinkpad_images/thinkpadt450.png",
            releaseDate = "Jan, 2015",
            series = "T Series",
            marketPriceStart = 250,
            marketPriceEnd = 500,
            processorPlatforms = "Intel 5th Gen",
            processors = "i5-4300u",
            graphics = "Intel HD 5500",
            maxRam = "16GB (2 Slots)",
            displayRes = "1366x768, 1600x900, 1920x1080",
            touchScreen = "Yes",
            screenSize = "14 inch",
            backlitKb = "Yes",
            fingerPrintReader = "Yes",
            kbType = "6 Row, Backlit",
            dualBatt = "Yes",
            internalBatt = "3 Cell",
            externalBatt = "3 Cell, 6 Cell",
            psrefLink = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosVersion = "1.37(JBET73WW)",
            knownIssues = "Other",
            knownIssuesLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            displaysSupported = "AUO, LG, SAM",
            otherMods = "Other",
            otherModsLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosLockIn = "Yes: Display"
        ),
        Thinkpad(
            model = "Thinkpad T450",
            imageUrl = "https://raw.githubusercontent.com/racka98/ThinkRchive/main/thinkpad_images/thinkpadt450.png",
            releaseDate = "Jan, 2015",
            series = "T Series",
            marketPriceStart = 250,
            marketPriceEnd = 500,
            processorPlatforms = "Intel 5th Gen",
            processors = "i5-4300u",
            graphics = "Intel HD 5500",
            maxRam = "16GB (2 Slots)",
            displayRes = "1366x768, 1600x900, 1920x1080",
            touchScreen = "Yes",
            screenSize = "14 inch",
            backlitKb = "Yes",
            fingerPrintReader = "Yes",
            kbType = "6 Row, Backlit",
            dualBatt = "Yes",
            internalBatt = "3 Cell",
            externalBatt = "3 Cell, 6 Cell",
            psrefLink = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosVersion = "1.37(JBET73WW)",
            knownIssues = "Other",
            knownIssuesLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            displaysSupported = "AUO, LG, SAM",
            otherMods = "Other",
            otherModsLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosLockIn = "Yes: Display"
        ),
        Thinkpad(
            model = "Thinkpad T450",
            imageUrl = "https://raw.githubusercontent.com/racka98/ThinkRchive/main/thinkpad_images/thinkpadt450.png",
            releaseDate = "Jan, 2015",
            series = "T Series",
            marketPriceStart = 250,
            marketPriceEnd = 500,
            processorPlatforms = "Intel 5th Gen",
            processors = "i5-4300u",
            graphics = "Intel HD 5500",
            maxRam = "16GB (2 Slots)",
            displayRes = "1366x768, 1600x900, 1920x1080",
            touchScreen = "Yes",
            screenSize = "14 inch",
            backlitKb = "Yes",
            fingerPrintReader = "Yes",
            kbType = "6 Row, Backlit",
            dualBatt = "Yes",
            internalBatt = "3 Cell",
            externalBatt = "3 Cell, 6 Cell",
            psrefLink = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosVersion = "1.37(JBET73WW)",
            knownIssues = "Other",
            knownIssuesLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            displaysSupported = "AUO, LG, SAM",
            otherMods = "Other",
            otherModsLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosLockIn = "Yes: Display"
        )
    )
}