package work.racka.thinkrchive.testUtils

import work.racka.thinkrchive.data.remote.responses.ThinkpadResponse

internal object FakeThinkpadData {

    val fakeResponseList = listOf(
        ThinkpadResponse(
            model = "Thinkpad T450",
            imageUrl = "https://raw.githubusercontent.com/racka98/ThinkRchive/main/thinkpad_images/thinkpadt450.png",
            releaseDate = "Jan, 2015",
            series = "T Series",
            marketPriceStart = 250,
            marketPriceEnd = 500,
            processorPlatforms = "Intel 5th Gen",
            processors = "i3-4030U, i5-4300U, i3-5010U, i5-5200U, i5-5300U, i7-5500U, i7-5600U",
            graphics = "Intel HD 5500",
            maxRam = "16GB (2 Slots)",
            displayRes = "1366x768, 1600x900, 1920x1080",
            touchScreen = "Yes",
            screenSize = "14 inch",
            backlitKb = "Yes",
            fingerPrintReader = "Yes",
            kbType = "6 Row, Backlit",
            dualBatt = "Yes",
            internalBatt = "3 Cell",
            externalBatt = "3 Cell, 6 Cell",
            psrefLink = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosVersion = "1.37(JBET73WW)",
            knownIssues = "Other",
            knownIssuesLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            displaysSupported = "AUO, LG, SAM",
            otherMods = "Other",
            otherModsLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosLockIn = "Yes: Display",
            ports = "3x USB 3.0, VGA, Mini DisplayPort, Ethernet (RJ-45), Dock connector, SD Card Reader"
        ),
        ThinkpadResponse(
            model = "Thinkpad T450s",
            imageUrl = "https://raw.githubusercontent.com/racka98/ThinkRchive/main/thinkpad_images/thinkpadt450.png",
            releaseDate = "Jan, 2015",
            series = "T Series",
            marketPriceStart = 250,
            marketPriceEnd = 500,
            processorPlatforms = "Intel 5th Gen",
            processors = "i5-4300u",
            graphics = "Intel HD 5500",
            maxRam = "16GB (2 Slots)",
            displayRes = "1366x768, 1600x900, 1920x1080",
            touchScreen = "Yes",
            screenSize = "14 inch",
            backlitKb = "Yes",
            fingerPrintReader = "Yes",
            kbType = "6 Row, Backlit",
            dualBatt = "Yes",
            internalBatt = "3 Cell",
            externalBatt = "3 Cell, 6 Cell",
            psrefLink = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosVersion = "1.37(JBET73WW)",
            knownIssues = "Other",
            knownIssuesLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            displaysSupported = "AUO, LG, SAM",
            otherMods = "Other",
            otherModsLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosLockIn = "Yes: Display",
            ports = "3x USB 3.0, VGA, Mini DisplayPort, Ethernet (RJ-45), Dock connector, SD Card Reader"
        ),
        ThinkpadResponse(
            model = "Thinkpad T460",
            imageUrl = "https://raw.githubusercontent.com/racka98/ThinkRchive/main/thinkpad_images/thinkpadt450.png",
            releaseDate = "Jan, 2016",
            series = "T Series",
            marketPriceStart = 250,
            marketPriceEnd = 500,
            processorPlatforms = "Intel 5th Gen",
            processors = "i5-4300u",
            graphics = "Intel HD 5500",
            maxRam = "16GB (2 Slots)",
            displayRes = "1366x768, 1600x900, 1920x1080",
            touchScreen = "Yes",
            screenSize = "14 inch",
            backlitKb = "Yes",
            fingerPrintReader = "Yes",
            kbType = "6 Row, Backlit",
            dualBatt = "Yes",
            internalBatt = "3 Cell",
            externalBatt = "3 Cell, 6 Cell",
            psrefLink = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosVersion = "1.37(JBET73WW)",
            knownIssues = "Other",
            knownIssuesLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            displaysSupported = "AUO, LG, SAM",
            otherMods = "Other",
            otherModsLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosLockIn = "Yes: Display",
            ports = "3x USB 3.0, VGA, Mini DisplayPort, Ethernet (RJ-45), Dock connector, SD Card Reader"
        ),
        ThinkpadResponse(
            model = "Thinkpad T460s",
            imageUrl = "https://raw.githubusercontent.com/racka98/ThinkRchive/main/thinkpad_images/thinkpadt450.png",
            releaseDate = "Jan, 2016",
            series = "T Series",
            marketPriceStart = 250,
            marketPriceEnd = 500,
            processorPlatforms = "Intel 5th Gen",
            processors = "i5-4300u",
            graphics = "Intel HD 5500",
            maxRam = "16GB (2 Slots)",
            displayRes = "1366x768, 1600x900, 1920x1080",
            touchScreen = "Yes",
            screenSize = "14 inch",
            backlitKb = "Yes",
            fingerPrintReader = "Yes",
            kbType = "6 Row, Backlit",
            dualBatt = "Yes",
            internalBatt = "3 Cell",
            externalBatt = "3 Cell, 6 Cell",
            psrefLink = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosVersion = "1.37(JBET73WW)",
            knownIssues = "Other",
            knownIssuesLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            displaysSupported = "AUO, LG, SAM",
            otherMods = "Other",
            otherModsLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosLockIn = "Yes: Display",
            ports = "3x USB 3.0, VGA, Mini DisplayPort, Ethernet (RJ-45), Dock connector, SD Card Reader"
        ),
        ThinkpadResponse(
            model = "Thinkpad T470",
            imageUrl = "https://raw.githubusercontent.com/racka98/ThinkRchive/main/thinkpad_images/thinkpadt450.png",
            releaseDate = "Jan, 2016",
            series = "T Series",
            marketPriceStart = 250,
            marketPriceEnd = 500,
            processorPlatforms = "Intel 5th Gen",
            processors = "i5-4300u",
            graphics = "Intel HD 5500",
            maxRam = "16GB (2 Slots)",
            displayRes = "1366x768, 1600x900, 1920x1080",
            touchScreen = "Yes",
            screenSize = "14 inch",
            backlitKb = "Yes",
            fingerPrintReader = "Yes",
            kbType = "6 Row, Backlit",
            dualBatt = "Yes",
            internalBatt = "3 Cell",
            externalBatt = "3 Cell, 6 Cell",
            psrefLink = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosVersion = "1.37(JBET73WW)",
            knownIssues = "Other",
            knownIssuesLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            displaysSupported = "AUO, LG, SAM",
            otherMods = "Other",
            otherModsLinks = "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T450/ThinkPad_T450_Spec.PDF",
            biosLockIn = "Yes: Display",
            ports = "3x USB 3.0, VGA, Mini DisplayPort, Ethernet (RJ-45), Dock connector, SD Card Reader"
        )
    )
}